[vm]
ubuntu_server ansible_host=127.0.0.1 ansible_port=2222 ansible_user=ubuntu-server ansible_ssh_private_key_file=~/.ssh/vm_key ansible_become_password=passer ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
